kind: Namespace
apiVersion: v1
metadata:
  name: testing-env
  labels:
    name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: test
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 8080
